import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="Next.js, HuntingCoder , " />
        
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      {/* <Script src="/  "></Script> */}
      
      <main className={styles.main}>
        <h2 className={styles.title}>
          Hunting Coders
        </h2>
        <p>
          A blog for a hunting programmer by a hunting coder
        </p>
        
        <div>
          <h2>Latest Blogs</h2>
          <div className='blogItem'>
             <h3>How to learn JavaScript in 2022 ?</h3>
             <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className='blogItem'>
             <h3>How to learn C++ in 2022 ?</h3>
             <p>C++ is the language used to design logic for the web</p>
          </div>
          <div className='blogItem'>
             <h3>How to learn Java in 2022 ?</h3>
             <p>Java is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
